[package]
name = "http"
# When releasing to crates.io:
# - Update html_root_url in lib.rs.
# - Update CHANGELOG.md.
# - Create git tag
version = "1.1.0"
readme = "README.md"
documentation = "https://docs.rs/http"
repository = "https://github.com/hyperium/http"
license = "MIT OR Apache-2.0"
authors = [
  "Alex Crichton <alex@alexcrichton.com>",
  "Carl Lerche <me@carllerche.com>",
  "Sean McArthur <sean@seanmonstar.com>",
]
description = """
A set of types for representing HTTP requests and responses.
"""
keywords = ["http"]
categories = ["web-programming"]
edition = "2021"
rust-version = "1.81.0"

[workspace]
members = ["."]
exclude = ["fuzz", "benches"]

[dependencies]
hashbrown = "0.15"
bytes = { version = "1", default-features = false }
fnv = { version = "1.0.5", default-features = false }
itoa = "1"

[dev-dependencies]
quickcheck = "1"
rand = "0.8.0"
serde = "1.0"
serde_json = "1.0"
doc-comment = "0.3"
